# Generated by Django 3.2.9 on 2021-11-29 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('locality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_adverse_reactions', models.BooleanField(default=False)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccinations', to='people.people')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('healthPersonnel', models.BooleanField(default=False)),
                ('canConsultingRoom', models.BooleanField(default=False)),
                ('canSchool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalHealth_Vaccination',
            fields=[
                ('vaccination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaccine.vaccination')),
                ('health_category', models.CharField(max_length=255)),
            ],
            bases=('vaccine.vaccination',),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vac_vaccinations', to='vaccine.vaccine'),
        ),
        migrations.CreateModel(
            name='Doce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doses', to='vaccine.vaccination')),
            ],
        ),
        migrations.CreateModel(
            name='School_Vaccination',
            fields=[
                ('vaccination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaccine.vaccination')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_vaccinations', to='locality.school')),
            ],
            bases=('vaccine.vaccination',),
        ),
        migrations.CreateModel(
            name='ConsultingRoom_Vaccination',
            fields=[
                ('vaccination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaccine.vaccination')),
                ('consulting_rooms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='con_vaccinations', to='locality.consultingroom')),
            ],
            bases=('vaccine.vaccination',),
        ),
    ]
