# Generated by Django 3.2.9 on 2021-11-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('healthPersonnel', models.BooleanField(default=False)),
                ('canConsultingRoom', models.BooleanField(default=False)),
                ('canSchool', models.BooleanField(default=False)),
            ],
        ),
    ]
