# Generated by Django 3.2.9 on 2021-11-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
