# Generated by Django 3.2.9 on 2021-11-25 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('locality', '0004_consultingroom'),
        ('vaccine', '0002_alter_vaccine_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adverse_reactions', models.TextField()),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccinations', to='people.people')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vac_vaccinations', to='vaccine.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalHealth_Vaccination',
            fields=[
                ('vaccination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaccine.vaccination')),
                ('health_category', models.CharField(max_length=255)),
            ],
            bases=('vaccine.vaccination',),
        ),
        migrations.CreateModel(
            name='School_Vaccination',
            fields=[
                ('vaccination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaccine.vaccination')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_vaccinations', to='locality.school')),
            ],
            bases=('vaccine.vaccination',),
        ),
        migrations.CreateModel(
            name='ConsultingRoom_Vaccination',
            fields=[
                ('vaccination_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vaccine.vaccination')),
                ('consulting_rooms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='con_vaccinations', to='locality.consultingroom')),
            ],
            bases=('vaccine.vaccination',),
        ),
    ]
