# Generated by Django 3.2.9 on 2021-11-26 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0003_consultingroom_vaccination_personalhealth_vaccination_school_vaccination_vaccination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doses', to='vaccine.vaccination')),
            ],
        ),
    ]
