# Generated by Django 3.2.9 on 2021-11-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0004_doce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='adverse_reactions',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='has_adverse_reactions',
            field=models.BooleanField(default=False),
        ),
    ]
