# Generated by Django 3.2.9 on 2021-11-23 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0003_polyclinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('polyclinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consulting_rooms', to='locality.polyclinic')),
            ],
        ),
    ]
