# Generated by Django 3.2.9 on 2021-11-24 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locality', '0004_consultingroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('ci', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_names', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('positive_pcr', models.BooleanField(blank=True, default=False, null=True)),
                ('date_pcr', models.DateField(blank=True, null=True)),
                ('consulting_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='locality.consultingroom')),
            ],
        ),
    ]
